# Gruvbox theme colors
thm_bg="#2e2a29"
thm_fg="#cbb890"
thm_cyan="#7db669"
thm_black="#1e1e1e"
thm_gray="#3f3935"
thm_magenta="#c77089"
thm_pink="#f73028"
thm_red="#890009"
thm_green="#aab01e"
thm_yellow="#f7b125"
thm_blue="#719586"
thm_orange="#fb6a16"
thm_black4="#534a42"

# Status bar
set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"
set-option -g status-position top

# Messages
set -g message-style "fg=${thm_green},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_green},bg=${thm_gray},align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

# Statusline - current window
set -g window-status-current-format "#[fg=${thm_green},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_green},nobold,nounderscore,noitalics]#I #[fg=${thm_fg},bg=${thm_gray}] #W#[fg=${thm_gray}]#[bg=${thm_bg}] "

# Statusline - other windows
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_blue},nobold,nounderscore,noitalics]#I #[fg=${thm_fg},bg=${thm_gray}] #W#[fg=${thm_gray}]#[bg=${thm_bg}] "

# Statusline - right side
set -g status-right "#{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_green}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_green}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_gray}] #S#[fg=${thm_gray}]#[bg=${thm_bg}] "

# Statusline - left side (empty)
set -g status-left " "

# Modes
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"
